allowBuilds:
  esbuild: true
  libav.js: true
  libav.js@https://codeload.github.com/Yahweasel/libav.js/tar.gz/c80e885c3461f7bb7ea565c9631b34243ae0dbf1(patch_hash=fd9ef806de503d54da90fc487835e8c42f2c57052a02133c1800a3fbb3d08fec): true
  sharp: true
  workerd: true
patchedDependencies:
  libav.js@6.10.9: patches/libav.js@6.10.9.patch
